workflows:
  android_webview_debug:
    name: Android Debug APK (Guru Maarif DH)
    max_build_duration: 30
    environment:
      android:
        components:
          - "platform-tools"
          - "build-tools;34.0.0"
          - "platforms;android-34"
          - "cmdline-tools;latest"
      java: 17
      vars:
        MODULE: app
    scripts:
      - name: Pastikan AndroidX ON (gradle.properties)
        script: |
          if [ ! -f gradle.properties ]; then
            cat > gradle.properties <<'PROP'
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.daemon=false
PROP
          else
            grep -q "android.useAndroidX=true" gradle.properties || echo "android.useAndroidX=true" >> gradle.properties
            grep -q "android.enableJetifier=true" gradle.properties || echo "android.enableJetifier=true" >> gradle.properties
          fi
          echo "=== gradle.properties ==="
          cat gradle.properties

      - name: Accept licenses & install komponen SDK
        script: |
          yes | sdkmanager --licenses || true
          sdkmanager --install "platform-tools" "cmdline-tools;latest" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK
        script: |
          gradle --no-daemon :$MODULE:assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
