workflows:
  android_webview_debug:
    name: Android Debug APK (Guru Maarif DH)
    max_build_duration: 30
    environment:
      android:
        # Minta Android SDK 34 & Build Tools 34
        components:
          - "platform-tools"
          - "build-tools;34.0.0"
          - "platforms;android-34"
          - "cmdline-tools;latest"
      java: 17
      vars:
        MODULE: app
    scripts:
      - name: Tampilkan struktur repo (cek posisi settings.gradle)
        script: |
          pwd
          ls -la
          test -f settings.gradle || (echo "settings.gradle tidak ketemu di root repo" && exit 1)

      - name: Pastikan AndroidX ON (gradle.properties)
        script: |
          if [ ! -f gradle.properties ]; then
            cat > gradle.properties <<'PROP'
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.daemon=false
PROP
          else
            # patch aman kalau belum ada flag
            grep -q "android.useAndroidX=true" gradle.properties || echo "android.useAndroidX=true" >> gradle.properties
            grep -q "android.enableJetifier=true" gradle.properties || echo "android.enableJetifier=true" >> gradle.properties
          fi
          echo "=== gradle.properties ==="
          cat gradle.properties

      - name: Accept licenses & install komponen SDK yang diminta
        script: |
          yes | sdkmanager --licenses || true
          sdkmanager --install "platform-tools" "cmdline-tools;latest" "platforms;android-34" "build-tools;34.0.0"

      - name: Setup Gradle (tanpa wrapper)
        script: |
          # Pakai gradle dari Codemagic; tidak pakai ./gradlew untuk menghindari error wrapper
          gradle --version

      - name: Build Debug APK
        script: |
          gradle --no-daemon :$MODULE:assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - **/outputs/**/*.aab
      - **/outputs/**/*.mapping.txt

    publishing:
      email:
        recipients:
          - "you@example.com"    # opsional: ganti email kamu biar APK dikirim otomatis
        notify:
          success: true
          failure: true

Add codemagic.yaml
