workflows:
  android_webview_debug:
    name: Android Debug APK (Guru Maarif DH)
    max_build_duration: 30
    environment:
      android:
        components:
          - "platform-tools"
          - "build-tools;34.0.0"
          - "platforms;android-34"
          - "cmdline-tools;latest"
      java: 17
      vars:
        MODULE: app
    scripts:
      - name: Accept licenses & install SDK
        script: |
          yes | sdkmanager --licenses || true
          sdkmanager --install "platform-tools" "cmdline-tools;latest" \
                               "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK
        script: |
          gradle --no-daemon :$MODULE:assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
