name: Build APK (Guru Maarif DH)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure unzip & JDK
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" \
                               "platforms;android-34" \
                               "build-tools;34.0.0" \
                               "cmdline-tools;latest"

      # ==== ZIP → Extract otomatis (biar bisa upload ZIP doang) ====
      - name: Extract project from ZIP (if present)
        id: extract
        run: |
          set -e
          if [ -f "GuruMaarifDH.zip" ]; then
            echo "ZIP found, extracting..."
            mkdir -p workspace
            unzip -q GuruMaarifDH.zip -d workspace
            # cari folder yang ada settings.gradle
            PROJECT_DIR=$(dirname $(find workspace -maxdepth 3 -name settings.gradle -print -quit))
          else
            echo "ZIP not found, assuming files already extracted."
            PROJECT_DIR=$(dirname $(find . -maxdepth 3 -name settings.gradle -print -quit))
          fi
          echo "project_dir=$PROJECT_DIR" >> $GITHUB_OUTPUT
          echo "Project dir: $PROJECT_DIR"
          test -n "$PROJECT_DIR"

      - name: Generate Gradle Wrapper (if missing)
        run: |
          cd "${{ steps.extract.outputs.project_dir }}"
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper missing → generating..."
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          else
            echo "Gradle wrapper exists."
          fi

      - name: Build Debug APK
        run: |
          cd "${{ steps.extract.outputs.project_dir }}"
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: GuruMaarifDH-debug-apk
          path: ${{ steps.extract.outputs.project_dir }}/app/build/outputs/apk/debug/app-debug.apk
